import re
import json

text = """
[Barus Julu](https://id.wikipedia.org/wiki/Barus_Julu,_Barusjahe,_Karo)
[Barusjahe](https://id.wikipedia.org/wiki/Barusjahe,_Barusjahe,_Karo)
[Bulan Jahe](https://id.wikipedia.org/wiki/Bulan_Jahe,_Barusjahe,_Karo)
[Bulan Julu](https://id.wikipedia.org/wiki/Bulan_Julu,_Barusjahe,_Karo)
[Paribun](https://id.wikipedia.org/wiki/Paribun,_Barusjahe,_Karo)
[Penampen](https://id.wikipedia.org/wiki/Penampen,_Barusjahe,_Karo)
[Persadanta](https://id.wikipedia.org/wiki/Persadanta,_Barusjahe,_Karo)
[Pertumbuken](https://id.wikipedia.org/wiki/Pertumbuken,_Barusjahe,_Karo)
[Rumamis](https://id.wikipedia.org/wiki/Rumamis,_Barusjahe,_Karo)
[Sarimanis](https://id.wikipedia.org/wiki/Sarimanis,_Barusjahe,_Karo)
[Semangat](https://id.wikipedia.org/wiki/Semangat,_Barusjahe,_Karo)
[Serdang](https://id.wikipedia.org/wiki/Serdang,_Barusjahe,_Karo)
[Sikab](https://id.wikipedia.org/wiki/Sikab,_Barusjahe,_Karo)
[Sinaman](https://id.wikipedia.org/wiki/Sinaman,_Barusjahe,_Karo)
[Sukajulu](https://id.wikipedia.org/wiki/Sukajulu,_Barusjahe,_Karo)
[Sukanalu](https://id.wikipedia.org/wiki/Sukanalu,_Barusjahe,_Karo)
[Talimbaru](https://id.wikipedia.org/wiki/Talimbaru,_Barusjahe,_Karo)
[Tangkidik](https://id.wikipedia.org/wiki/Tangkidik,_Barusjahe,_Karo)
[Tanjung Barus](https://id.wikipedia.org/wiki/Tanjung_Barus,_Barusjahe,_Karo)
[Daulu](https://id.wikipedia.org/wiki/Daulu,_Berastagi,_Karo)
[Gurusinga](https://id.wikipedia.org/wiki/Gurusinga,_Berastagi,_Karo)
[Lau Gumba](https://id.wikipedia.org/wiki/Lau_Gumba,_Berastagi,_Karo)
[Raya](https://id.wikipedia.org/wiki/Raya,_Berastagi,_Karo)
[Rumah Berastagi](https://id.wikipedia.org/wiki/Rumah_Berastagi,_Berastagi,_Karo)
[Sempajaya](https://id.wikipedia.org/wiki/Sempajaya,_Berastagi,_Karo)
[Gundaling I](https://id.wikipedia.org/wiki/Gundaling_I,_Berastagi,_Karo)
[Gundaling Ii](https://id.wikipedia.org/wiki/Gundaling_II,_Berastagi,_Karo)
[Tambak Lau Mulgap I](https://id.wikipedia.org/wiki/Tambak_Lau_Mulgap_I,_Berastagi,_Karo)
[Tambak Lau Mulgap Ii](https://id.wikipedia.org/wiki/Tambak_Lau_Mulgap_II,_Berastagi,_Karo)
[Bukit](https://id.wikipedia.org/wiki/Bukit,_Dolat_Rayat,_Karo)
[Dolat Rayat](https://id.wikipedia.org/wiki/Dolat_Rayat,_Dolat_Rayat,_Karo)
[Kubucolia](https://id.wikipedia.org/wiki/Kubucolia,_Dolat_Rayat,_Karo)
[Melas](https://id.wikipedia.org/wiki/Melas,_Dolat_Rayat,_Karo)
[Sampun](https://id.wikipedia.org/wiki/Sampun,_Dolat_Rayat,_Karo)
[Sugihen](https://id.wikipedia.org/wiki/Sugihen,_Dolat_Rayat,_Karo)
[Ujung Sampun](https://id.wikipedia.org/wiki/Ujung_Sampun,_Dolat_Rayat,_Karo)
[Batu Mamak](https://id.wikipedia.org/wiki/Batu_Mamak,_Juhar,_Karo)
[Bekilang](https://id.wikipedia.org/wiki/Bekilang,_Juhar,_Karo)
[Buluh Pancur](https://id.wikipedia.org/wiki/Buluh_Pancur,_Juhar,_Karo)
[Gunung Juhar](https://id.wikipedia.org/wiki/Gunung_Juhar,_Juhar,_Karo)
[Jandi](https://id.wikipedia.org/wiki/Jandi,_Juhar,_Karo)
[Juhar Ginting](https://id.wikipedia.org/wiki/Juhar_Ginting,_Juhar,_Karo)
[Juhar Ginting Sadanioga](https://id.wikipedia.org/wiki/Juhar_Ginting_Sadanioga,_Juhar,_Karo)
[Juhar Perangin-angin](https://id.wikipedia.org/wiki/Juhar_Perangin-angin,_Juhar,_Karo)
[Juhar Tarigan](https://id.wikipedia.org/wiki/Juhar_Tarigan,_Juhar,_Karo)
[Keriahen](https://id.wikipedia.org/wiki/Keriahen,_Juhar,_Karo)
[Ketawaren](https://id.wikipedia.org/wiki/Ketawaren,_Juhar,_Karo)
[Kidupen](https://id.wikipedia.org/wiki/Kidupen,_Juhar,_Karo)
[Kutagugung](https://id.wikipedia.org/wiki/Kutagugung,_Juhar,_Karo)
[Kutambelin](https://id.wikipedia.org/wiki/Kutambelin,_Juhar,_Karo)
[Lau Kidupen](https://id.wikipedia.org/wiki/Lau_Kidupen,_Juhar,_Karo)
[Lau Lingga](https://id.wikipedia.org/wiki/Lau_Lingga,_Juhar,_Karo)
[Mbetung](https://id.wikipedia.org/wiki/Mbetung,_Juhar,_Karo)
[Naga](https://id.wikipedia.org/wiki/Naga,_Juhar,_Karo)
[Nageri](https://id.wikipedia.org/wiki/Nageri,_Juhar,_Karo)
[Namosuro](https://id.wikipedia.org/wiki/Namosuro,_Juhar,_Karo)
[Pasar Baru](https://id.wikipedia.org/wiki/Pasar_Baru,_Juhar,_Karo)
[Pernantin](https://id.wikipedia.org/wiki/Pernantin,_Juhar,_Karo)
[Sigenderang](https://id.wikipedia.org/wiki/Sigenderang,_Juhar,_Karo)
[Sugihen](https://id.wikipedia.org/wiki/Sugihen,_Juhar,_Karo)
[Sukababo](https://id.wikipedia.org/wiki/Sukababo,_Juhar,_Karo)
[Kaban](https://id.wikipedia.org/wiki/Kaban,_Kabanjahe,_Karo)
[Kacaribu](https://id.wikipedia.org/wiki/Kacaribu,_Kabanjahe,_Karo)
[Kandibata](https://id.wikipedia.org/wiki/Kandibata,_Kabanjahe,_Karo)
[Ketaren](https://id.wikipedia.org/wiki/Ketaren,_Kabanjahe,_Karo)
[Lausimono](https://id.wikipedia.org/wiki/Lausimono,_Kabanjahe,_Karo)
[Rumah Kabanjahe](https://id.wikipedia.org/wiki/Rumah_Kabanjahe,_Kabanjahe,_Karo)
[Samura](https://id.wikipedia.org/wiki/Samura,_Kabanjahe,_Karo)
[Sumber Mufakat](https://id.wikipedia.org/wiki/Sumber_Mufakat,_Kabanjahe,_Karo)
[Gung Leto](https://id.wikipedia.org/wiki/Gung_Leto,_Kabanjahe,_Karo)
[Gung Negeri](https://id.wikipedia.org/wiki/Gung_Negeri,_Kabanjahe,_Karo)
[Kampung Dalam](https://id.wikipedia.org/wiki/Kampung_Dalam,_Kabanjahe,_Karo)
[Lau Cimba](https://id.wikipedia.org/wiki/Lau_Cimba,_Kabanjahe,_Karo)
[Padang Mas](https://id.wikipedia.org/wiki/Padang_Mas,_Kabanjahe,_Karo)
[Bintang Meriah](https://id.wikipedia.org/wiki/Bintang_Meriah,_Kuta_Buluh,_Karo)
[Buah Raya](https://id.wikipedia.org/wiki/Buah_Raya,_Kuta_Buluh,_Karo)
[Gunung Meriah](https://id.wikipedia.org/wiki/Gunung_Meriah,_Kuta_Buluh,_Karo)
[Jinabun](https://id.wikipedia.org/wiki/Jinabun,_Kuta_Buluh,_Karo)
[Kutabuluh](https://id.wikipedia.org/wiki/Kutabuluh,_Kuta_Buluh,_Karo?action=edit&redlink=1)
[Kutabuluh Gugung](https://id.wikipedia.org/wiki/Kutabuluh_Gugung,_Kuta_Buluh,_Karo?action=edit&redlink=1)
[Kuta Male](https://id.wikipedia.org/wiki/Kuta_Male,_Kuta_Buluh,_Karo)
[Lau Buluh](https://id.wikipedia.org/wiki/Lau_Buluh,_Kuta_Buluh,_Karo)
[Liang Merdeka](https://id.wikipedia.org/wiki/Liang_Merdeka,_Kuta_Buluh,_Karo)
[Mburidi](https://id.wikipedia.org/wiki/Mburidi,_Kuta_Buluh,_Karo)
[Negeri Jahe](https://id.wikipedia.org/wiki/Negeri_Jahe,_Kuta_Buluh,_Karo)
[Pola Tebu](https://id.wikipedia.org/wiki/Pola_Tebu,_Kuta_Buluh,_Karo)
[Rih Tengah](https://id.wikipedia.org/wiki/Rih_Tengah,_Kuta_Buluh,_Karo)
[Siabang Abang](https://id.wikipedia.org/wiki/Siabang_Abang,_Kuta_Buluh,_Karo)
[Tanjung Merahe](https://id.wikipedia.org/wiki/Tanjung_Merahe,_Kuta_Buluh,_Karo)
[Ujung Deleng](https://id.wikipedia.org/wiki/Ujung_Deleng,_Kuta_Buluh,_Karo)
[Buluh Pancur](https://id.wikipedia.org/wiki/Buluh_Pancur,_Laubaleng,_Karo)
[Batu Rongkam](https://id.wikipedia.org/wiki/Batu_Rongkam,_Laubaleng,_Karo?action=edit&redlink=1)
[Durin Rugun](https://id.wikipedia.org/wiki/Durin_Rugun,_Laubaleng,_Karo)
[Kinangkong](https://id.wikipedia.org/wiki/Kinangkong,_Laubaleng,_Karo)
[Kutambelin](https://id.wikipedia.org/wiki/Kutambelin,_Laubaleng,_Karo)
[Lau Baleng](https://id.wikipedia.org/wiki/Lau_Baleng,_Laubaleng,_Karo)
[Lau Peradep](https://id.wikipedia.org/wiki/Lau_Peradep,_Laubaleng,_Karo)
[Lau Peranggunan](https://id.wikipedia.org/wiki/Lau_Peranggunan,_Laubaleng,_Karo)
[Lingga Muda](https://id.wikipedia.org/wiki/Lingga_Muda,_Laubaleng,_Karo)
[Martelu](https://id.wikipedia.org/wiki/Martelu,_Laubaleng,_Karo)
[Mbal-mbal Petarum](https://id.wikipedia.org/wiki/Mbal-mbal_Petarum,_Laubaleng,_Karo)
[Perbulan](https://id.wikipedia.org/wiki/Perbulan,_Laubaleng,_Karo)
[Pintu Angin](https://id.wikipedia.org/wiki/Pintu_Angin,_Laubaleng,_Karo?action=edit&redlink=1)
[Rambah Tampu](https://id.wikipedia.org/wiki/Rambah_Tampu,_Laubaleng,_Karo)
[Tanjung Gunung](https://id.wikipedia.org/wiki/Tanjung_Gunung,_Laubaleng,_Karo)
[Bandar Purba](https://id.wikipedia.org/wiki/Bandar_Purba,_Mardingding,_Karo)
[Bukit Makmur](https://id.wikipedia.org/wiki/Bukit_Makmur,_Mardingding,_Karo?action=edit&redlink=1)
[Kuta Pengkih](https://id.wikipedia.org/wiki/Kuta_Pengkih,_Mardingding,_Karo)
[Lau Garut](https://id.wikipedia.org/wiki/Lau_Garut,_Mardingding,_Karo?action=edit&redlink=1)
[Lau Kasumpat](https://id.wikipedia.org/wiki/Lau_Kasumpat,_Mardingding,_Karo)
[Lau Mulgap](https://id.wikipedia.org/wiki/Lau_Mulgap,_Mardingding,_Karo)
[Lau Pakam](https://id.wikipedia.org/wiki/Lau_Pakam,_Mardingding,_Karo)
[Lau Pengulu](https://id.wikipedia.org/wiki/Lau_Pengulu,_Mardingding,_Karo)
[Lau Solu](https://id.wikipedia.org/wiki/Lau_Solu,_Mardingding,_Karo)
[Mardingding](https://id.wikipedia.org/wiki/Mardingding,_Mardingding,_Karo)
[Rimo Bunga](https://id.wikipedia.org/wiki/Rimo_Bunga,_Mardingding,_Karo)
[Tanjung Pamah](https://id.wikipedia.org/wiki/Tanjung_Pamah,_Mardingding,_Karo)
[Cinta Rayat](https://id.wikipedia.org/wiki/Cinta_Rayat,_Merdeka,_Karo)
[Deram](https://id.wikipedia.org/wiki/Deram,_Merdeka,_Karo)
[Gongsol](https://id.wikipedia.org/wiki/Gongsol,_Merdeka,_Karo)
[Jaranguda](https://id.wikipedia.org/wiki/Jaranguda,_Merdeka,_Karo)
[Merdeka](https://id.wikipedia.org/wiki/Merdeka,_Merdeka,_Karo)
[Sada Perarih](https://id.wikipedia.org/wiki/Sada_Perarih,_Merdeka,_Karo)
[Semangat](https://id.wikipedia.org/wiki/Semangat,_Merdeka,_Karo)
[Semangat Gunung](https://id.wikipedia.org/wiki/Semangat_Gunung,_Merdeka,_Karo)
[Ujung Teran](https://id.wikipedia.org/wiki/Ujung_Teran,_Merdeka,_Karo)
[Ajinembah](https://id.wikipedia.org/wiki/Ajinembah,_Merek,_Karo)
[Bandar Tongging](https://id.wikipedia.org/wiki/Bandar_Tongging,_Merek,_Karo)
[Dokan](https://id.wikipedia.org/wiki/Dokan,_Merek,_Karo)
[Garingging](https://id.wikipedia.org/wiki/Garingging,_Merek,_Karo)
[Kodon-kodon](https://id.wikipedia.org/wiki/Kodon-kodon,_Merek,_Karo)
[Merek](https://id.wikipedia.org/wiki/Merek,_Merek,_Karo)
[Mulia Rakyat](https://id.wikipedia.org/wiki/Mulia_Rakyat,_Merek,_Karo)
[Nagalingga](https://id.wikipedia.org/wiki/Nagalingga,_Merek,_Karo)
[Nagara](https://id.wikipedia.org/wiki/Nagara,_Merek,_Karo)
[Negeri Tongging](https://id.wikipedia.org/wiki/Negeri_Tongging,_Merek,_Karo)
[Pancur Batu](https://id.wikipedia.org/wiki/Pancur_Batu,_Merek,_Karo)
[Pangambaten](https://id.wikipedia.org/wiki/Pangambaten,_Merek,_Karo)
[Pertibi Lama](https://id.wikipedia.org/wiki/Pertibi_Lama,_Merek,_Karo)
[Pertibitembe](https://id.wikipedia.org/wiki/Pertibitembe,_Merek,_Karo)
[Regaji](https://id.wikipedia.org/wiki/Regaji,_Merek,_Karo)
[Sibolangit](https://id.wikipedia.org/wiki/Sibolangit,_Merek,_Karo)
[Situnggaling](https://id.wikipedia.org/wiki/Situnggaling,_Merek,_Karo)
[Sukamandi](https://id.wikipedia.org/wiki/Sukamandi,_Merek,_Karo)
[Tongging](https://id.wikipedia.org/wiki/Tongging,_Merek,_Karo)
[Bandar Meriah](https://id.wikipedia.org/wiki/Bandar_Meriah,_Munte,_Karo)
[Barung Kersap](https://id.wikipedia.org/wiki/Barung_Kersap,_Munte,_Karo)
[Biak Nampe](https://id.wikipedia.org/wiki/Biak_Nampe,_Munte,_Karo)
[Buluh Naman](https://id.wikipedia.org/wiki/Buluh_Naman,_Munte,_Karo)
[Gunung Manumpak](https://id.wikipedia.org/wiki/Gunung_Manumpak,_Munte,_Karo)
[Gunung Saribu](https://id.wikipedia.org/wiki/Gunung_Saribu,_Munte,_Karo)
[Gurubenua](https://id.wikipedia.org/wiki/Gurubenua,_Munte,_Karo?action=edit&redlink=1)
[Kabantua](https://id.wikipedia.org/wiki/Kabantua,_Munte,_Karo)
[Kineppen](https://id.wikipedia.org/wiki/Kineppen,_Munte,_Karo)
[Kutagerat](https://id.wikipedia.org/wiki/Kutagerat,_Munte,_Karo)
[Kutambaru](https://id.wikipedia.org/wiki/Kutambaru,_Munte,_Karo)
[Kutasuah](https://id.wikipedia.org/wiki/Kutasuah,_Munte,_Karo)
[Munthe](https://id.wikipedia.org/wiki/Munthe,_Munte,_Karo)
[Nageri](https://id.wikipedia.org/wiki/Nageri,_Munte,_Karo)
[Parimbalang](https://id.wikipedia.org/wiki/Parimbalang,_Munte,_Karo)
[Pertumbungen](https://id.wikipedia.org/wiki/Pertumbungen,_Munte,_Karo)
[Sarimunte](https://id.wikipedia.org/wiki/Sarimunte,_Munte,_Karo)
[Sarinembah](https://id.wikipedia.org/wiki/Sarinembah,_Munte,_Karo)
[Selakkar](https://id.wikipedia.org/wiki/Selakkar,_Munte,_Karo)
[Singgamanik](https://id.wikipedia.org/wiki/Singgamanik,_Munte,_Karo)
[Sukarame](https://id.wikipedia.org/wiki/Sukarame,_Munte,_Karo)
[Tanjung Beringin](https://id.wikipedia.org/wiki/Tanjung_Beringin,_Munte,_Karo)
[Bekerah](https://id.wikipedia.org/wiki/Bekerah,_Naman_Teran,_Karo)
[Gung Pinto](https://id.wikipedia.org/wiki/Gung_Pinto,_Naman_Teran,_Karo)
[Kebayaken](https://id.wikipedia.org/wiki/Kebayaken,_Naman_Teran,_Karo)
[Kuta Gugung](https://id.wikipedia.org/wiki/Kuta_Gugung,_Naman_Teran,_Karo)
[Kuta Mbelin](https://id.wikipedia.org/wiki/Kuta_Mbelin,_Naman_Teran,_Karo)
[Kuta Rayat](https://id.wikipedia.org/wiki/Kuta_Rayat,_Naman_Teran,_Karo)
[Kuta Tonggal](https://id.wikipedia.org/wiki/Kuta_Tonggal,_Naman_Teran,_Karo)
[Naman](https://id.wikipedia.org/wiki/Naman,_Naman_Teran,_Karo)
[Ndeskati](https://id.wikipedia.org/wiki/Ndeskati,_Naman_Teran,_Karo)
[Sigarang Garang](https://id.wikipedia.org/wiki/Sigarang_Garang,_Naman_Teran,_Karo)
[Simacem](https://id.wikipedia.org/wiki/Simacem,_Naman_Teran,_Karo)
[Suka Nalu](https://id.wikipedia.org/wiki/Suka_Nalu,_Naman_Teran,_Karo)
[Suka Ndebi](https://id.wikipedia.org/wiki/Suka_Ndebi,_Naman_Teran,_Karo)
[Sukatepu](https://id.wikipedia.org/wiki/Sukatepu,_Naman_Teran,_Karo)
[Batukarang](https://id.wikipedia.org/wiki/Batukarang,_Payung,_Karo)
[Cimbang](https://id.wikipedia.org/wiki/Cimbang,_Payung,_Karo)
[Gurukinayan](https://id.wikipedia.org/wiki/Gurukinayan,_Payung,_Karo)
[Payung](https://id.wikipedia.org/wiki/Payung,_Payung,_Karo)
[Rimokayu](https://id.wikipedia.org/wiki/Rimokayu,_Payung,_Karo)
[Selandi](https://id.wikipedia.org/wiki/Selandi,_Payung,_Karo)
[Suka Meriah](https://id.wikipedia.org/wiki/Suka_Meriah,_Payung,_Karo)
[Ujung Payung](https://id.wikipedia.org/wiki/Ujung_Payung,_Payung,_Karo)
[Beganding](https://id.wikipedia.org/wiki/Beganding,_Simpang_Empat,_Karo)
[Berastepu](https://id.wikipedia.org/wiki/Berastepu,_Simpang_Empat,_Karo)
[Bulan Baru](https://id.wikipedia.org/wiki/Bulan_Baru,_Simpang_Empat,_Karo)
[Gajah](https://id.wikipedia.org/wiki/Gajah,_Simpang_Empat,_Karo)
[Gamber](https://id.wikipedia.org/wiki/Gamber,_Simpang_Empat,_Karo)
[Jeraya](https://id.wikipedia.org/wiki/Jeraya,_Simpang_Empat,_Karo)
[Kuta Tengah](https://id.wikipedia.org/wiki/Kuta_Tengah,_Simpang_Empat,_Karo)
[Lingga](https://id.wikipedia.org/wiki/Lingga,_Simpang_Empat,_Karo)
[Lingga Julu](https://id.wikipedia.org/wiki/Lingga_Julu,_Simpang_Empat,_Karo)
[Nang Belawan](https://id.wikipedia.org/wiki/Nang_Belawan,_Simpang_Empat,_Karo)
[Ndokum Siroga](https://id.wikipedia.org/wiki/Ndokum_Siroga,_Simpang_Empat,_Karo)
[Perteguhen](https://id.wikipedia.org/wiki/Perteguhen,_Simpang_Empat,_Karo)
[Pintu Besi](https://id.wikipedia.org/wiki/Pintu_Besi,_Simpang_Empat,_Karo)
[Serumbia](https://id.wikipedia.org/wiki/Serumbia,_Simpang_Empat,_Karo)
[Surbakti](https://id.wikipedia.org/wiki/Surbakti,_Simpang_Empat,_Karo)
[Tiga Pancur](https://id.wikipedia.org/wiki/Tiga_Pancur,_Simpang_Empat,_Karo)
[Torong](https://id.wikipedia.org/wiki/Torong,_Simpang_Empat,_Karo)
[Batumamak](https://id.wikipedia.org/wiki/Batumamak,_Tigabinanga,_Karo?action=edit&redlink=1)
[Bunga Baru](https://id.wikipedia.org/wiki/Bunga_Baru,_Tigabinanga,_Karo)
[Gunung](https://id.wikipedia.org/wiki/Gunung,_Tigabinanga,_Karo)
[Kem-kem](https://id.wikipedia.org/wiki/Kem-kem,_Tigabinanga,_Karo)
[Kuala](https://id.wikipedia.org/wiki/Kuala,_Tigabinanga,_Karo)
[Kuta Bangun](https://id.wikipedia.org/wiki/Kuta_Bangun,_Tigabinanga,_Karo)
[Kuta Buara](https://id.wikipedia.org/wiki/Kuta_Buara,_Tigabinanga,_Karo)
[Kuta Galoh](https://id.wikipedia.org/wiki/Kuta_Galoh,_Tigabinanga,_Karo)
[Kuta Gerat](https://id.wikipedia.org/wiki/Kuta_Gerat,_Tigabinanga,_Karo)
[Kuta Julu](https://id.wikipedia.org/wiki/Kuta_Julu,_Tigabinanga,_Karo)
[Kuta Raya](https://id.wikipedia.org/wiki/Kuta_Raya,_Tigabinanga,_Karo)
[Kutambaru Punti Batu Mama](https://id.wikipedia.org/wiki/Kutambaru_Punti_Batu_Mama,_Tigabinanga,_Karo)
[Lau Kapur](https://id.wikipedia.org/wiki/Lau_Kapur,_Tigabinanga,_Karo)
[Limang](https://id.wikipedia.org/wiki/Limang,_Tigabinanga,_Karo)
[Perbesi](https://id.wikipedia.org/wiki/Perbesi,_Tigabinanga,_Karo)
[Pergendangen](https://id.wikipedia.org/wiki/Pergendangen,_Tigabinanga,_Karo)
[Pertumbuken](https://id.wikipedia.org/wiki/Pertumbuken,_Tigabinanga,_Karo)
[Simolap](https://id.wikipedia.org/wiki/Simolap,_Tigabinanga,_Karo)
[Simpang Pergendangen Perlambe](https://id.wikipedia.org/wiki/Simpang_Pergendangen_Perlambe,_Tigabinanga,_Karo)
[Tigabinanga](https://id.wikipedia.org/wiki/Tigabinanga,_Tigabinanga,_Karo)
[Gunung Merlawan](https://id.wikipedia.org/wiki/Gunung_Merlawan,_Tiganderket,_Karo)
[Jandi Meriah](https://id.wikipedia.org/wiki/Jandi_Meriah,_Tiganderket,_Karo)
[Kuta Kepar](https://id.wikipedia.org/wiki/Kuta_Kepar,_Tiganderket,_Karo)
[Kutagaluh](https://id.wikipedia.org/wiki/Kutagaluh,_Tiganderket,_Karo)
[Kutambaru](https://id.wikipedia.org/wiki/Kutambaru,_Tiganderket,_Karo)
[Mardingding](https://id.wikipedia.org/wiki/Mardingding,_Tiganderket,_Karo)
[Nari Gunung Dua](https://id.wikipedia.org/wiki/Nari_Gunung_Dua,_Tiganderket,_Karo)
[Nari Gunung Satu](https://id.wikipedia.org/wiki/Nari_Gunung_Satu,_Tiganderket,_Karo)
[Penampen](https://id.wikipedia.org/wiki/Penampen,_Tiganderket,_Karo)
[Perbaji](https://id.wikipedia.org/wiki/Perbaji,_Tiganderket,_Karo)
[Suka Tendel](https://id.wikipedia.org/wiki/Suka_Tendel,_Tiganderket,_Karo)
[Susuk](https://id.wikipedia.org/wiki/Susuk,_Tiganderket,_Karo)
[Tanjung Mbelang](https://id.wikipedia.org/wiki/Tanjung_Mbelang,_Tiganderket,_Karo)
[Tanjung Merawa](https://id.wikipedia.org/wiki/Tanjung_Merawa,_Tiganderket,_Karo)
[Tanjung Pulo](https://id.wikipedia.org/wiki/Tanjung_Pulo,_Tiganderket,_Karo)
[Temburun](https://id.wikipedia.org/wiki/Temburun,_Tiganderket,_Karo)
[Tiganderket](https://id.wikipedia.org/wiki/Tiganderket,_Tiganderket,_Karo)
[Ajibuhara](https://id.wikipedia.org/wiki/Ajibuhara,_Tigapanah,_Karo)
[Ajijahe](https://id.wikipedia.org/wiki/Ajijahe,_Tigapanah,_Karo)
[Ajijulu](https://id.wikipedia.org/wiki/Ajijulu,_Tigapanah,_Karo)
[Ajimbelang](https://id.wikipedia.org/wiki/Ajimbelang,_Tigapanah,_Karo)
[Bertah](https://id.wikipedia.org/wiki/Bertah,_Tigapanah,_Karo)
[Bekerah](https://id.wikipedia.org/wiki/Bekerah,_Tigapanah,_Karo?action=edit&redlink=1)
[Bunuraya](https://id.wikipedia.org/wiki/Bunuraya,_Tigapanah,_Karo)
[Kacinambun](https://id.wikipedia.org/wiki/Kacinambun,_Tigapanah,_Karo)
[Kubusimbelang](https://id.wikipedia.org/wiki/Kubusimbelang,_Tigapanah,_Karo)
[Kutabale](https://id.wikipedia.org/wiki/Kutabale,_Tigapanah,_Karo)
[Kutakepar](https://id.wikipedia.org/wiki/Kutakepar,_Tigapanah,_Karo)
[Kutambelin](https://id.wikipedia.org/wiki/Kutambelin,_Tigapanah,_Karo)
[Kutajulu](https://id.wikipedia.org/wiki/Kutajulu,_Tigapanah,_Karo)
[Lambar](https://id.wikipedia.org/wiki/Lambar,_Tigapanah,_Karo?action=edit&redlink=1)
[Lauriman](https://id.wikipedia.org/wiki/Lauriman,_Tigapanah,_Karo)
[Lepar Samura](https://id.wikipedia.org/wiki/Lepar_Samura,_Tigapanah,_Karo)
[Manuk Mulia](https://id.wikipedia.org/wiki/Manuk_Mulia,_Tigapanah,_Karo)
[Mulawari](https://id.wikipedia.org/wiki/Mulawari,_Tigapanah,_Karo)
[Salit](https://id.wikipedia.org/wiki/Salit,_Tigapanah,_Karo?action=edit&redlink=1)
[Seberaya](https://id.wikipedia.org/wiki/Seberaya,_Tigapanah,_Karo)
[Simacem](https://id.wikipedia.org/wiki/Simacem,_Tigapanah,_Karo?action=edit&redlink=1)
[Singa](https://id.wikipedia.org/wiki/Singa,_Tigapanah,_Karo)
[Suka](https://id.wikipedia.org/wiki/Suka,_Tigapanah,_Karo)
[Sukadame](https://id.wikipedia.org/wiki/Sukadame,_Tigapanah,_Karo)
[Sukamaju](https://id.wikipedia.org/wiki/Sukamaju,_Tigapanah,_Karo)
[Suka Mbayak](https://id.wikipedia.org/wiki/Suka_Mbayak,_Tigapanah,_Karo?action=edit&redlink=1)
[Suka Sipilihen](https://id.wikipedia.org/wiki/Suka_Sipilihen,_Tigapanah,_Karo?action=edit&redlink=1)
[Sukameriah](https://id.wikipedia.org/wiki/Sukameriah,_Tigapanah,_Karo?action=edit&redlink=1)
[Tigapanah](https://id.wikipedia.org/wiki/Tigapanah,_Tigapanah,_Karo)
"""

villages = []

for line in text.split('\n'):
    line = line.strip()
    if not line:
        continue
    
    match = re.match(r'\[(.*?)\]\((.*?)\)', line)
    if match:
        name = match.group(1).strip()
        url = match.group(2)
        
        parts = url.split('/')[-1].replace('%20', '_').split(',')
        if len(parts) >= 3:
            kecamatan = parts[1].replace('_', ' ').strip()
        elif len(parts) == 2:
            kecamatan = parts[0].replace('_', ' ').strip()
        else:
            kecamatan = "Karo"
            
        search_query = f"Desa {name}, Kecamatan {kecamatan}, Kabupaten Karo"
        # special handling for Berastagi / Kabanjahe where they might be Kelurahan instead of Desa, 
        # but Nominatim usually finds them better without "Desa" if they are Kelurahan.
        # But we'll just keep it simple: `name, kecamatan, Karo` is often best.
        villages.append({
            "name": name,
            "kecamatan": kecamatan,
            "full_name": f"{name}, Kec. {kecamatan}",
            "search_query": f"{name}, {kecamatan}, Kabupaten Karo, Sumatera Utara"
        })

with open('public/karo_villages.json', 'w') as f:
    json.dump(villages, f, indent=4)

print(f"Extracted {len(villages)} villages.")
